import type { ImgHTMLAttributes } from 'react';

/** Responsive widths generated by optimize-images.mjs into public/img/<kind>/. */
const WIDTHS = {
  projects: [480, 800],
  portraits: [420, 840],
} as const;

type Kind = keyof typeof WIDTHS;

interface PictureProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'sizes' | 'width' | 'height'> {
  kind: Kind;
  /** File name without extension or width suffix, e.g. "Hero". */
  name: string;
  /** Intrinsic size of the largest variant, so the browser can reserve space (no layout shift). */
  width: number;
  height: number;
  sizes: string;
  /** Marks an above-the-fold (LCP) image: eager load + high fetch priority. */
  priority?: boolean;
}

/** AVIF → WebP responsive <picture> with explicit dimensions and lazy decoding. */
export function Picture({ kind, name, width, height, sizes, priority = false, alt = '', ...rest }: PictureProps) {
  const widths = WIDTHS[kind];
  const base = `/img/${kind}/${name}`;
  const set = (ext: string) => widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ');
  return (
    <picture>
      <source type="image/avif" srcSet={set('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={set('webp')} sizes={sizes} />
      <img
        src={`${base}-${widths[widths.length - 1]}.webp`}
        srcSet={set('webp')}
        sizes={sizes}
        width={width}
        height={height}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        fetchPriority={priority ? 'high' : 'auto'}
        {...rest}
      />
    </picture>
  );
}
